/*
MapMarkers Minecraft Bukkit plugin for showing Essentials warps 
and warp events on maps generated by Minecraft Overviewer.
Copyright (C) 2011 Brendan Johan Lee 
Email: brendan (at) vanntett.net

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, 
MA  02110-1301, USA.
*/

package is.brendan.WarpMarkers;

import java.util.logging.*;

import org.bukkit.Server;
import org.bukkit.command.CommandSender;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.PluginCommand;
import org.bukkit.plugin.*;
import org.bukkit.plugin.java.*;
import org.bukkit.entity.Player;

import com.earth2me.essentials.Warps;

/**
 * Dirty dirty hacky executor 
 *
 * @author Brendan Johan Lee - deadcyclo@vanntett.net
 */

public class WarpMarkersCommandTrap implements CommandExecutor {
    private final WarpMarkers plugin;
    private final CommandExecutor exec;
    private final PluginCommand origin;
    private final WarpMarkers wm;

    public WarpMarkersCommandTrap(WarpMarkers plugin, CommandExecutor exec, PluginCommand origin, WarpMarkers wm) {
	this.plugin = plugin;
	this.exec = exec;
	this.origin = origin;
	this.wm = wm;
    }

    public boolean onCommand(CommandSender sender, Command cmd, String commandLabel, String[] args){
	this.origin.setExecutor(exec);
	boolean result = this.origin.execute(sender, commandLabel, args);
	this.origin.setExecutor(this);
	wm.handleCommand(sender, cmd, commandLabel, args);
	return result;
    }
}